name: Build and deploy Node.js app to Azure Web App - zoldosveny

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install and Build Frontend
        run: |
          npm install --force
          npm run build
        working-directory: ./frontend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2EE023CBCF314926B2A17B2344B749C8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_998D40C9866A4C7F9E7F30290E2C5037 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B1DA46112A5746929667328667244BB3 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zoldosveny'
          slot-name: 'Production'
          package: .